### ISSUE TITLE
download ansible from a commit 

### ISSUE THREAD

**Issue by redarqas** [novafloss/ansible-setup#16]
To be able to do

```
bash ansible-setup ansible_ref_require cdec853
```

**Comment by redarqas** [comment]
hi @jpic any news on that ?

**Comment by ccouturi** [comment]
Je n'ai probablement pas tout les détails alors je résume, et dites moi si je me trompe :

Actuellement lors d'une installation d'Ansible avec ce script, nous récupérons le dernier build ansible disponible.
Et ce qu'on aimerait c'est pouvoir spécifier une version stable précise pour être moins impacté au quotidien.

Correct ?

**Comment by jpic** [comment]
Oui, vous serez moins impacté au quotidien, car vous n'aurez pas à supporter les updates upstream au fur et à mesure qu'elles arrivent.

Par contre demain, quand vous aurez besoin de mettre à jour, il faudra se tapper toutes les updates d'un coup ... c'est une configuration dangereuse car elle facilite la mise en retard des upgrades.

**Comment by ccouturi** [comment]
Existe t-il une solution intermédiaire pour récupérer des versions "stables" avec une fréquence moindre ?
Effectivement le risque de pinner une version est de ne jamais ou rarement la mettre à jour.

**Comment by jpic** [comment]
Pour le stable, j'utilise ansible_ref_require stable-2.2, c'est pas déjà ce que vous utilisez ?

Après concernant la faisabilité technique malheureusement github ne supporte pas le [téléchargement de tarball de commit](https://github.com/blog/12-tarball-downloads). Donc si on implémente par commit, il faudra utiliser git et ça sera un peu moins rapide.

**Comment by jpic** [comment]
Est-ce-que quelqu'un veut bien tester avec la #18 ?

Merci

**Comment by jpic** [comment]
Merci de m'avoir repingué au fait :)

**Comment by jpic** [comment]
je ferme car j'ai
