### ISSUE TITLE
changes in the .bashrc too intrusive?

### ISSUE THREAD

**Issue by brunobord** [novafloss/ansible-setup#2]
IMHO, [these changes done in the .bashrc](https://github.com/novafloss/ansible-setup/blob/master/setup.sh#L130-L134) are a bit too intrusive:

```
# User doesn't have a default virtualenv, let's configure one
if [ ! -f ~/.bashrc ] || ! grep 'source.*activate' ~/.bashrc; then
    echo '# Activate ansible virtualenv' >> ~/.bashrc
    echo 'source ~/.ansible-env/bin/activate' >> ~/.bashrc
    echo '!! You need to login again for changes to take effect !!'
fi
```

I don't have a default virtualenv _and_ I don't want one, whether it is "ansible-env" or not.
I agree that this change might be useful for people, so it doesn't have to be removed from the .sh script, but I'd prefer it to be subject to an option flag or a question, if this script could be interactive.

What do you think?

**Comment by jpic** [comment]
Perhaps if you add something like this to .bashrc ?

```
# Marker to prevent ansible-setup from adding its source venv/bin/activate
```

**Comment by toopy** [comment]
@jpic I want to kill you for that!

**Comment by jpic** [comment]
@toopy you're over-reacting :)

**Comment by bersace** [comment]
Je pense que c'est bon avec ansible-setup. À rouvrir si besoin.
