### ISSUE TITLE
Update git submodules too?

### ISSUE THREAD

**Issue by indispeq** [novafloss/ansible-setup#5]
It seems that in order to update everything one has to not just update the git repo but go into the venv/src/ansible/lib/ansible/modules and do a git submodule update --init.

It seems to be the most common error why certain roles fail, even if we re-run ansible-setup. @jpic do you think it's worth explicitly doing this in every run of setup.sh ?

**Comment by bersace** [comment]
Je pense que c'est obsolète avec le nouvel `ansible-setup` à rouvrir se besoin.
